[package]
name          = "safe_dns"
version       = "0.2.1"
authors       = ["MaidSafe Developers <dev@maidsafe.net>"]
description   = "SAFE DNS API library"
documentation = "http://maidsafe.net/safe_dns/latest"
repository    = "https://github.com/maidsafe/safe_dns"
readme        = "README.md"
license       = "GPL-3.0"
homepage      = "http://maidsafe.net"

[dependencies]
# ---- Maidsafe ----
routing         = "0.4.*"
#safe_nfs        = "0.2.*"
#safe_core       = "0.2.*"

# ---- Others ----
log             = "*"
sodiumoxide     = "*"
rustc-serialize = "*"

[dev-dependencies]
regex = "*"

[dependencies.safe_core]
path = "/home/spandan/virtualization/coding/rust-maidsafe/maidsafe-core/safe_core"

[dependencies.safe_nfs]
path = "/home/spandan/virtualization/coding/rust-maidsafe/maidsafe-nfs/safe_nfs"

[features]
use-mock-routing = ["safe_core/use-mock-routing",
                    "safe_nfs/use-mock-routing"]
