[package]
name          = "maidsafe_dns"
version       = "0.0.1"
authors       = ["MaidSafe Developers <dev@maidsafe.net>"]
description   = "Maidsafe DNS API library"
documentation = "http://maidsafe.net/maidsafe_dns/latest"
repository    = "https://github.com/maidsafe/maidsafe_dns"
readme        = "README.md"
license       = "GPL-3.0"
homepage      = "http://maidsafe.net"

[dependencies]
# ---- Maidsafe ----
routing         = "*"
maidsafe_client = "*"

# ---- Others ----
cbor            = "*"
sodiumoxide     = "*"
rustc-serialize = "*"

[features]
USE_ACTUAL_ROUTING = ["maidsafe_client/USE_ACTUAL_ROUTING"]
