[package]
name          = "safe_dns"
version       = "0.1.0"
authors       = ["MaidSafe Developers <dev@maidsafe.net>"]
description   = "SAFE DNS API library"
documentation = "http://maidsafe.net/safe_dns/latest"
repository    = "https://github.com/maidsafe/safe_dns"
readme        = "README.md"
license       = "GPL-3.0"
homepage      = "http://maidsafe.net"

[dependencies]
# ---- Maidsafe ----
routing         = "0.3.*"
#safe_nfs        = "0.1.*"
#safe_client     = "0.1.*"

# ---- Others ----
log             = "*"
sodiumoxide     = "*"
rustc-serialize = "*"

[dev-dependencies]
regex = "*"

[dependencies.safe_nfs]
git = "https://github.com/maidsafe/safe_nfs"

[dependencies.safe_client]
git = "https://github.com/maidsafe/safe_client"

[features]
use-mock-routing = ["safe_client/use-mock-routing",
                    "safe_nfs/use-mock-routing"]
